export enum ErrorCode {
  // Generic errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  SAME_PASSWORD = 'SAME_PASSWORD',

  // Setup errors
  SETUP_ALREADY_COMPLETED = 'SETUP_ALREADY_COMPLETED',
}
